config/routes.rb
Rails.application.routes.draw do
  root to: 'top_page#index'
  resources :top_page, onry: [:index]
  resources :profile, onry: [:index]
  resources :skill, onry: [:index]
  resources :portfolio, onry: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end
end

app/controllers/skill_controller.rb
class SkillController < ApplicationController
  def index
  end
end

app/controllers/top_page_controller.rb
class TopPageController < ApplicationController
  def index
  end
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/skill_helper.rb
module SkillHelper
end

app/helpers/top_page_helper.rb
module TopPageHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyPage
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}
    %link{:href => "https://use.fontawesome.com/releases/v5.12.0/css/all.css", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/earlyaccess/nicomoji.css", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Alfa+Slab+One&display=swap", :rel => "stylesheet"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = yield

app/views/portfolio/_first__page.html.haml
-# .first__page
-#   .first__page__header yarender
-#   .return-home-btn 戻る
-#   %ul.app-box-right
-#     %li.app-discription
-#       アプリの説明:
-#       %br/
-#       %br/
-#       ToDoアプリです。
-#       %br/
-#       Trelloみたいなレイアウトを目指して
-#       %br/
-#       見易いポップな仕上がりにしてみました。
-#     %li.app-skil
-#       使用したスキル:
-#       %br/
-#       ruby,html,css,RubyonRails,git
-#       %br/
-#       AWS(EC2,IAM,MFA),Nginx,Capistrano等
-#     %li.app-other
-#       備考:
-#       %br/
-#       今後は、webpackによってVue.jsを導入して
-#       %br/
-#       ドラッグ＆ドロップ機能を付けること、
-#       %br/
-#       カレンダーページから,その日のToDo画面に遷移、
-#       %br/
-#       その日のリスト名をカレンダーに表示させるように
-#       %br/
-#       仕上げていく予定です。
-#       %br/
-#       %br/
-#       <テストアカウント>
-#       %br/
-#       メールアドレス: kk@kk.com
-#       %br/
-#       パスワード: kkkkkkk
-#   %ul.app-box-left
-#     %li.image-box
-#     %li.yarender-btn アプリ起動



-# :javascript
-#   $(function() {
-#     $(".return-home-btn").click(function() {
-#       if (confirm('トップページへ戻りますか？')) {
-#         window.location.href = '/';
-#       }
-#     });
-#     $(".yarender-btn").click(function() {
-#       window.location.href = 'http://18.176.26.126';
-#     });
-#   });

app/views/portfolio/_fourth__page.html.haml
.fourth__page
  .fourth__page__header furima
  %ul.app-box-right
    %li.app-discription
      アプリの説明:
      %br/
      %br/
      駆け出し仲間とアジャイルチーム開発で作った
      %br/
      フリマアプリです。
      %br/
      チーム開発の楽しさと難しさ、チーム開発でのgitの使い方などを知ることが出来ました。
      %br/
      %br/
      担当箇所
      %br/
      ⇩⇩⇩
      %br/
      ● DB設計
      %br/
      ① 本アプリケーションのシステムに必要なエンティティの
      %br/
      洗い出し及び定義
      %br/
      ② dependemtオプション等を利用した各テーブル同士の
      %br/
      アソシエーション定義
      %br/
      ③ ER図及びREADMEの作成
      %br/
      ④ 各モデルやマイグレーションファイルの作成
      %br/
      ⑤ enum型を利用した商品状態や出品状態の定義
      %br/
      ● 商品一覧表示（サーバーサイド、マークアップ）
      %br/
      ● 商品購入確認ページ（サーバーサイド、マークアップ）
      %br/
      ● 商品削除機能（サーバーサイド）
      %br/
      ● マイページ（サイドバー部分）
      %br/
      %br/
      ★　工夫した点
      %br/
      ① 進捗状況を共有しながら開発を行えるように、定期的にミーティングを行い、GitKrakenの導入やToreroを活用しました。
      %br/
      ② チームの仲間が苦戦している場合は、自身の担当箇所の進捗状況と見合わせながらヘルプに入りました。
      %br/
      ③ チーム開発をよりスムーズに行える様に、仲間同士でのコミュニケーションを大事にしました。
      %br/
      ④ どうしても分からずチーム開発に支障を来たす虞のある場合は、見切りをつけて仲間に協力を求めるようにしました。
      %br/
      ⑤ 自身の進捗状況やブランチの動きは、スクラムリーダーに逐一報告して把握して貰える様に努めました。
      %br/
      %br/
      ★　苦労した点
      %br/
      ● 仲間に協力を求める際のポイント
      %br/
      相手に自身の状況や分からない部分を説明するときは、コードを全て把握して一行一行説明出来るように調べた上で聞くことが大切であると学びました。
      %br/
      自身の頭の中で現在の状況を整理して調べていくことで、相手に質問する前に自己解決出来ることが増えました。
      %br/
      ● データベース設計
      %br/
      必要なテーブルの洗い出しや、各テーブル同士の関係性を定義することに非常に苦労しました。
      %br/
      多階層カテゴリー機能に対するデータベース設計も、設計方法が分からずに苦労しましたが、
      %br/
      調べていく中でancestryというgemを利用すれば、
      %br/
      簡易的に機能を実装出来ることを知り、カテゴリー機能を担当する仲間の負担を増やさず進めることが出来ました。
      %br/
      バリデーションを考えたり、決められた入力文字のみを受け付けらる様に正規表現を用いたり、
      %br/
      一つのテーブルが冗長にならない様に住所テーブルを別に設けたり、不要なカラムを選別したり、
      %br/
      アプリケーション開発においてデータベース設計がどれほど重要なものであるかを身をもって体験することが出来ました。
      %br/
      実装したい機能の行方について入念に考慮することにより、アプリケーション作成に必要な構想力を高めることが出来ました。
    %li.app-skil
      使用したスキル:
      %br/
      バックエンド
      %br/
      Ruby
      %br/
      フロントエンド
      %br/
      HTML,CSS,Javascript(jQuery)
      %br/
      RubyonRails(テストフレームワーク:Rspec)
      %br/
      インフラ構築
      %br/
      AWS(EC2,S3),Nginx
      %br/
      Capistrano
      %br/
      DB
      %br
      MySQL
      %br/
      その他
      %br/
      Git,Trello,Slack
    %li.app-other
      備考:
      %br/
      %br/
      <テストアカウント>
      %br/
      メールアドレス: w@w.com
      %br/
      パスワード: aaaaaaa

  %ul.app-box-left
    %li.image-box
    %li.furima-btn アプリ起動



:javascript
  $(function() {

    $(".furima-btn").click(function() {
      window.location.href = 'http://52.198.162.19/';
    });
  });

app/views/portfolio/_second__page.html.haml
.second__page
  .second__page__header PickTweet
  %ul.app-box-right
    %li.app-discription
      アプリの説明:
      %br/
      %br/
      Tweetアプリです。
      %br/
      好きな写真とコメントを投稿出来ます。
      %br/
      マイページへ遷移して、
      %br/
      自分だけの投稿履歴を閲覧することも出来ます。
      %br/
      コメント文を対象にした検索機能も付けてみました。
      %br/
    %li.app-skil
      使用したスキル:
      %br/
      バックエンド
      %br/
      Ruby
      %br/
      フロントエンド
      %br/
      HTML,CSS,Javascript(Jquery)
      %br/
      フレームワーク
      %br/
      RubyonRails(テストフレームワーク:Rspec)
      %br/
      インフラ構築
      %br/
      AWS(EC2,S3,IAM,MFA),Nginx
      %br/
      CD
      %br/
      capistrono
      %br/
      DB
      %br/
      MySQL
      %br/
      その他
      %br/
      Git,Trello
    %li.app-other
      <テストアカウント>
      %br/
      メールアドレス: kk@kk.com
      %br/
      パスワード: kkkkkkk
  %ul.app-box-left
    %li.image-box
    %li.pictweet-btn アプリ起動



:javascript
  $(function() {

    $(".pictweet-btn").click(function() {
      window.location.href = 'http://18.180.161.233/';
    });
  });

app/views/portfolio/_third__page.html.haml
.third__page
  .third__page__header Our memories
  %ul.app-box-right
    %li.app-discription
      アプリの説明:
      %br/
      %br/
      ユーザーが日記の様に思い出を写真付きで投稿できます。
      %br/
    %li.app-skil
      使用したスキル:
      %br/
      バックエンド
      %br/
      PHP
      %br/
      フロントエンド
      %br/
      HTML,CSS(bootstrap),Javascript
      %br/
      フレームワーク
      %br/
      Laravel
      %br/
      インフラ構築
      %br/
      AWS(EC2,RDS,Route53,IAM,MFA,ELB,Cloud9)
      %br/
      Nginx
      %br/
      CD
      %br/
      Capistrano
      %br/
      DB
      %br
      MySQL
      %br/
      その他
      %br/
      Git,Trello
    %li.app-other
      <テストアカウント>
      %br/
      メールアドレス: kk@kk.com
      %br/
      パスワード: kkkkkkkk
  %ul.app-box-left
    %li.image-box
    %li.board-btn アプリ起動



:javascript
  $(function() {

    $(".board-btn").click(function() {
      window.location.href = 'http://52.198.144.70/';
    });
  });

app/views/portfolio/index.html.haml
.portfolio__pages
  = render 'portfolio/first__page'
  = render 'portfolio/third__page'
  = render 'portfolio/second__page'
  = render 'portfolio/fourth__page'

app/views/skill/index.html.haml
= render 'top_page/header'
.skill__page
  .return-home-btn 戻る
  %ul.first-stage
    %li.skill-html HTML
    %li.skill-css CSS
    %li.skill-ruby Ruby
  %ul.second-stage
    %li.skill-rails Ruby on Rails
    %li.skill-javascript Javascript
    %li.skill-jquery Jquery
  %ul.third-stage
    %li.skill-vue Vue.js
    %li.skill-nuxt Nuxt.js
    %li.skill-git Git
  %ul.last-stage
    %li.skill-mysql MySQL
    %li.skill-AWS AWS
    %li.skill-investigation 犯罪捜査

:javascript
  $(function() {
    $(".return-home-btn").click(function() {
      if (confirm('トップページへ戻りますか？')) {
        window.location.href = '/';
      }
    });

    $('.skill-html').hover(function(){
      $(this).text('Haml使えます');
      $(this).css({
        'font-size': '30px'
      });
    },function(){
      $(this).text('HTML');
      $(this).css({
        'font-size': '50px'
      });
    });

    $('.skill-css').hover(function(){
      $(this).text('Sass使えます');
      $(this).css({
        'font-size': '30px'
      });
    },function(){
      $(this).text('CSS');
      $(this).css({
        'font-size': '50px'
      });
    });

    $('.skill-ruby').hover(function(){
      $(this).text('ロゴかわいい');
      $(this).css({
        'font-size': '30px',
        'font-weight': 'bold'
      });
    },function(){
      $(this).text('Ruby');
      $(this).css({
        'font-size': '50px'
      });
    });

    $('.skill-rails').hover(function(){
      $(this).text('使い易い！');
      $(this).css({
        'font-size': '50px'
      });
    },function(){
      $(this).text('Ruby on Rails');
      $(this).css({
        'font-size': '30px'
      });
    });

    $('.skill-javascript').hover(function(){
      $(this).text('奥深い！');
      $(this).css({
        'font-size': '50px'
      });
    },function(){
      $(this).text('Javascript');
      $(this).css({
        'font-size': '50px'
      });
    });

    $('.skill-jquery').hover(function(){
      $(this).text('覚えて良かった！');
      $(this).css({
        'font-size': '30px'
      });
    },function(){
      $(this).text('Jquary');
      $(this).css({
        'font-size': '50px'
      });
    });

  $('.skill-vue').hover(function(){
      $(this).text('コンポーネントまじ便利');
      $(this).css({
        'font-size': '25px',
        'text-shadow': '1px 1px 1px black'
      });
    },function(){
      $(this).text('Vue.js');
      $(this).css({
        'font-size': '50px',
        'text-shadow': '6px 4px 1px rgb(5, 37, 30)'
      });
    });

    $('.skill-nuxt').hover(function(){
      $(this).text('Vuex猛勉強中！');
      $(this).css({
        'font-size': '30px',
      });
    },function(){
      $(this).text('Nuxt.js');
      $(this).css({
        'font-size': '50px'
      });
    });

    $('.skill-git').hover(function(){
      $(this).text('チーム開発経験済み');
      $(this).css({
        'font-size': '30px',
        'text-shadow': '1px 1px 1px orangered'
      });
    },function(){
      $(this).text('Git');
      $(this).css({
        'font-size': '50px',
        'text-shadow': '3px 3px 1px orangered'
      });
    });

    $('.skill-mysql').hover(function(){
      $(this).text('DB設計一番重要');
      $(this).css({
        'font-size': '30px',
        'text-shadow': '1px 1px 1px orangered'
      });
    },function(){
      $(this).text('MySQL');
      $(this).css({
        'font-size': '50px',
        'text-shadow': '3px 3px 1px orangered'
      });
    });

    $('.skill-AWS').hover(function(){
      $(this).text('EC2・S3!');
      $(this).css({
        'font-size': '40px',
      });
    },function(){
      $(this).text('AWS');
      $(this).css({
        'font-size': '50px'
      });
    });

    $('.skill-investigation').hover(function(){
      $(this).text('内容は秘密です');
      $(this).css({
        'font-size': '30px',
      });
    },function(){
      $(this).text('犯罪捜査');
      $(this).css({
        'font-size': '50px'
      });
    });
  });

app/views/top_page/_container.html.haml
.home-wrapper__container
  .push-btn push
.before__home-wrapper__container
  %h1.first_typing#typing
  %h1.second_typing#typing
  .home-wrapper__link-box
    #circle
    %i.fab.fa-gitkraken.fa-3x
      %h1.can-click Can you click me?
    %ul.link-box__left
      %li.link-box__profile
        = link_to("Profile", profile_index_path, {class: "profile-font"})
      %li.link-box__skill
        = link_to("Skill", skill_index_path, {class: "skill-font"})
    %ul.link-box__right
      %li.link-box__portfolio
        = link_to("Portfolio",portfolio_index_path, {class: "portfolio-font"})
      %li.link-box__qiita
        = link_to("Qiita","https://qiita.com/ki-ra-co", {class: "qiita-font"})
  %h1.description


:javascript
  $(function() {
    $('.push-btn').on('click',function(){
      $('.home-wrapper__container').css('display','none');
      $('.before__home-wrapper__container').css('display','block');
      const first_typing = (element, sentence) => {
        [...sentence].forEach((character, index) => {
          setTimeout(() => {
            document.querySelector(element).textContent += character;
         }, 200 * +index);
        });
      }
      const second_typing = (element, sentence) => {
        [...sentence].forEach((character, index) => {
          setTimeout(() => {
            document.querySelector(element).textContent += character;
         }, 300 * +index);
        });
      }
      first_typing('.first_typing', 'Hello! I am Koutaku Kihara');
      second_typing('.second_typing', 'Thanks for coming');
    });
    $('.link-box__profile').hover(function(){
      $(this).parents('.before__home-wrapper__container').find('.description').css({
        'display':'block',
      }).text("私の経歴を見ますか？");
    }, function() {
        $(this).parents('.before__home-wrapper__container').find('.description').css('display', 'none');
    });
    $('.link-box__skill').hover(function(){
      $(this).parents('.before__home-wrapper__container').find('.description').css({
        'display':'block',
      }).text("私のスキルセットです");
    }, function() {
        $(this).parents('.before__home-wrapper__container').find('.description').css('display', 'none');
    });
    $('.link-box__portfolio').hover(function(){
      $(this).parents('.before__home-wrapper__container').find('.description').css({
        'display':'block',
      }).text("私が作ったアプリを見ますか？");
    }, function() {
        $(this).parents('.before__home-wrapper__container').find('.description').css('display', 'none');
    });
    $('.link-box__qiita').hover(function(){
      $(this).parents('.before__home-wrapper__container').find('.description').css({
        'display':'block',
      }).text("お粗末ですが私のQiitaです");
    }, function() {
        $(this).parents('.before__home-wrapper__container').find('.description').css('display', 'none');
    });
    $('.fab.fa-gitkraken').on('click',function(){
      $('.can-click').text("GYAAAA!!!").css('color','red');
      setTimeout(function(){
        $('.description').css({
          'display':'block',
        }).text("撃破！");
      });
      setTimeout(function(){
        $('.description').css({
          'display':'none',
        }).text("撃破！");
      },1500);
      setTimeout(function(){
        $('.fab.fa-gitkraken').css('display','none');
      },2500);
      setTimeout(function(){
        $('.fab.fa-gitkraken').css('display','block');
        $('.can-click').text("Don't click sorry...").css('color','rgb(58, 116, 202)');
      },5000);
    });
  });

app/views/top_page/_header.html.haml
.home-wrapper__header
  %h1.header-title Welcome!MyPage!

app/views/top_page/index.html.haml
%body
  .home-wrapper
    = render 'header'
    = render 'container'